// import 'package:cripto/models/moedas.dart';

// class MoedaRepository {
//   static List<Moeda> tabela = [
//     Moeda(
//         icone: 'images/bitcoin.png',
//         nome: 'Bitcoin',
//         sigla: 'BTC',
//         preco: 1509.00,
//         baseId: '',
//         timestamp: null,
//         mudancaHora: null,
//         mudancaDia: null,
//         mudancaSemana: null,
//         mudancaMes: null,
//         mudancaAno: null,
//         mudancaPeriodoTotal: null),
//     Moeda(
//         icone: 'images/bitcoin.png',
//         nome: 'Bitcoin',
//         sigla: 'BTC',
//         preco: 1509.00,
//         baseId: '',
//         timestamp: null,
//         mudancaHora: null,
//         mudancaDia: null,
//         mudancaSemana: null,
//         mudancaMes: null,
//         mudancaAno: null,
//         mudancaPeriodoTotal: null),
//     Moeda(
//         icone: 'images/bitcoin.png',
//         nome: 'Bitcoin',
//         sigla: 'BTC',
//         preco: 1509.00,
//         baseId: '',
//         timestamp: null,
//         mudancaHora: null,
//         mudancaDia: null,
//         mudancaSemana: null,
//         mudancaMes: null,
//         mudancaAno: null,
//         mudancaPeriodoTotal: null),
//     Moeda(
//         icone: 'images/bitcoin.png',
//         nome: 'Bitcoin',
//         sigla: 'BTC',
//         preco: 1509.00,
//         baseId: '',
//         timestamp: null,
//         mudancaHora: null,
//         mudancaDia: null,
//         mudancaSemana: null,
//         mudancaMes: null,
//         mudancaAno: null,
//         mudancaPeriodoTotal: null),
//     Moeda(
//         icone: 'images/bitcoin.png',
//         nome: 'Bitcoin',
//         sigla: 'BTC',
//         preco: 1509.00,
//         baseId: '',
//         timestamp: null,
//         mudancaHora: null,
//         mudancaDia: null,
//         mudancaSemana: null,
//         mudancaMes: null,
//         mudancaAno: null,
//         mudancaPeriodoTotal: null),
//   ];
// }
